// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlSdpdMd-WsgHefsD2RGAlzSgejOwV1kw',
    appId: '1:844959482709:web:fc500ba237046b461fa5dc',
    messagingSenderId: '844959482709',
    projectId: 'activities-tracker-project',
    authDomain: 'activities-tracker-project.firebaseapp.com',
    storageBucket: 'activities-tracker-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8tZsfiPxC2gw6ZiF6heBa5BbtJzigsE',
    appId: '1:844959482709:android:51314f17784a28271fa5dc',
    messagingSenderId: '844959482709',
    projectId: 'activities-tracker-project',
    storageBucket: 'activities-tracker-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW6n_XIvUvjdMyh7CMj6XJInUM-oOGBZ0',
    appId: '1:844959482709:ios:7fcc8ceb8856a4fe1fa5dc',
    messagingSenderId: '844959482709',
    projectId: 'activities-tracker-project',
    storageBucket: 'activities-tracker-project.appspot.com',
    iosClientId: '844959482709-uc7ugtdlj5a5gtqat94cnh2va5hpaki3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW6n_XIvUvjdMyh7CMj6XJInUM-oOGBZ0',
    appId: '1:844959482709:ios:54492a340bd723331fa5dc',
    messagingSenderId: '844959482709',
    projectId: 'activities-tracker-project',
    storageBucket: 'activities-tracker-project.appspot.com',
    iosClientId: '844959482709-6ltgbsppcecda555uc8fi9niqb7rmsfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
